#!/usr/bin/env bash
# Start an interactive shell in the bloom-cargo-test container.
# The debian/ tree is pre-generated by the image build (Path 2).
# Inside the container, run ./build_debian_variant.sh or
# ./build_rosdebian_variant.sh; produced .debs land in /output/, which is
# bind-mounted to ../output/ on the host so the inspector container (and
# you) can see them.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="$SCRIPT_DIR/../output"
mkdir -p "$OUTPUT_DIR"

docker run --rm -it \
    -v "$OUTPUT_DIR:/output" \
    bloom-cargo-test
